version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: reward-mysql
    environment:
      MYSQL_ROOT_PASSWORD: avi123
      MYSQL_DATABASE: reward_system
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  backend:
    build: ./backend/reward-system
    container_name: reward-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always

  frontend:
    build: ./frontend/reward-system
    container_name: reward-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql-data:
